import ModifiedCartan

/-! Full local theorem audit. This is not a proof of the open paper targets. -/

#print axioms ModifiedCartan.compactConvergence_iff
#print axioms ModifiedCartan.compactConvergence_mono
#print axioms ModifiedCartan.compactConvergence_pointwise
#print axioms ModifiedCartan.cclass_nonempty
#print axioms ModifiedCartan.cclass_mono
#print axioms ModifiedCartan.cclass_card_ge_two
#print axioms ModifiedCartan.partitionProperty_mono
#print axioms ModifiedCartan.coefficients_zero_of_moments
#print axioms ModifiedCartan.exponentialSum_iteratedDeriv
#print axioms ModifiedCartan.exponentialSum_derivatives_at_zero
#print axioms ModifiedCartan.moments_zero_of_exponentialSum_zero
#print axioms ModifiedCartan.exponentialSum_zero_iff_coefficients
#print axioms ModifiedCartan.exponentialSum_zero_iff_finite_moments
#print axioms ModifiedCartan.exponentialSum_grouping
#print axioms ModifiedCartan.exponentialSum_zero_iff_grouped
#print axioms ModifiedCartan.moment_grouping
#print axioms ModifiedCartan.exponentialSum_zero_iff_moments
#print axioms ModifiedCartan.exponentialOrbit_at_zero
#print axioms ModifiedCartan.exponentialOrbit_nonzero
#print axioms ModifiedCartan.exponentialOrbit_hasDerivAt
#print axioms ModifiedCartan.growth_lemma
#print axioms ModifiedCartan.growthLemma_proved
#print axioms ModifiedCartan.poissonDenom_pos
#print axioms ModifiedCartan.poissonKernel_pos
#print axioms ModifiedCartan.kernel_factorization
#print axioms ModifiedCartan.kernel_boundary_nonneg
#print axioms ModifiedCartan.weightedKernel_difference
#print axioms ModifiedCartan.weightedKernel_antitone
#print axioms ModifiedCartan.weightedKernel_strict
#print axioms ModifiedCartan.weightedKernel_at_sharp
#print axioms ModifiedCartan.twoPointKernel_strict_aux
#print axioms ModifiedCartan.twoPointKernel_strict
#print axioms ModifiedCartan.twoPointKernel_uniform
#print axioms ModifiedCartan.kobayashiRoyden_le_of_disc
#print axioms ModifiedCartan.kobayashiRoyden_zero_of_orbit
#print axioms ModifiedCartan.laurentMonomial_on_orbit
#print axioms ModifiedCartan.laurent_eval_on_orbit
#print axioms ModifiedCartan.laurent_orbit_zero_iff_finite_equations
#print axioms ModifiedCartan.sharpRadius_pos
#print axioms ModifiedCartan.sharpRadius_lt_one
#print axioms ModifiedCartan.sharpRadius_quadratic
#print axioms ModifiedCartan.sharpRadius_ratio
#print axioms ModifiedCartan.sharpRadius_log_diameter
#print axioms ModifiedCartan.eta_pos
#print axioms ModifiedCartan.eta_le_one
#print axioms ModifiedCartan.absorptionRadius_pos
#print axioms ModifiedCartan.absorptionRadius_step
#print axioms ModifiedCartan.absorptionRadius_antitone
#print axioms ModifiedCartan.absorption_constant_bound
#print axioms ModifiedCartan.descending_count_bound
#print axioms ModifiedCartan.count_stabilization
#print axioms ModifiedCartan.wronskian_one
#print axioms ModifiedCartan.wronskian_const_mul
#print axioms ModifiedCartan.wronskian_common_const
#print axioms ModifiedCartan.wronskian_zero_of_linear_relation
#print axioms ModifiedCartan.diskSupNorm_nonneg
#print axioms ModifiedCartan.diskSupNorm_mono
#print axioms ModifiedCartan.leastCombinationNorm_le_first
#print axioms ModifiedCartan.quantitativeWronskian_one
